title: Antropomorphic Prostheses Control
author: Alexander Kobelev
email: ak.mail.ru@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This work is dedicated neuromuscular interface, which is based on electrical impedance 
  and surface electromyogram registered together. 
  Active part of impedance is registered non-invasively using tetrapolar electrode system 
  from a segment of the upper limb. 
  Impedance signals are proportional to the movement’s extent. 
  In contrast to other techniques, this approach allows anthropomorphic bioelectric prosthesis control.

# social links
github_username:  ak-git

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
