title: Antropomorphic Prostheses Control
author: Alexander Kobelev
email: ak.mail.ru@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This work is dedicated neuromuscular interface, which is based on electrical impedance 
  and surface electromyogram registered together. 
  In contrast to other techniques, this approach allows anthropomorphic bioelectric prosthesis control.

# social links
github_username:  ak-git

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
